#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TreasureAndroid.Resource", IsApplication=true)]

namespace TreasureAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int action_buttons = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int action_down = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int action_left = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int action_right = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int action_up = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int game_text = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int height_bar = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int height_bar_layout = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int height_bar_name = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int height_bar_value = 2131034128;
			
			// aapt resource value: 0x7f050022
			public const int loading_spinner = 2131034146;
			
			// aapt resource value: 0x7f050017
			public const int player_bar = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int player_bar_layout = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int player_bar_name = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int player_bar_value = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int portal_bar = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int portal_bar_layout = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int portal_bar_name = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int portal_bar_value = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int root = 2131034112;
			
			// aapt resource value: 0x7f050021
			public const int start_game = 2131034145;
			
			// aapt resource value: 0x7f050008
			public const int start_new_game = 2131034120;
			
			// aapt resource value: 0x7f05001b
			public const int swamp_bar = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int swamp_bar_layout = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int swamp_bar_name = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int swamp_bar_value = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int swamp_size_bar = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int swamp_size_bar_layout = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int swamp_size_bar_name = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int swamp_size_bar_value = 2131034144;
			
			// aapt resource value: 0x7f05000b
			public const int width_bar = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int width_bar_layout = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int width_bar_name = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int width_bar_value = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int winner_text = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_game_over = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_game_settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int action_go = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int action_strike = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int down = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int height = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int left = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int new_game = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int player_count = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int portal_count = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int right = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int start_game = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int swamp_count = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int swamp_size = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int up = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int width = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
