#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TreasureAndroid.Resource", IsApplication=true)]

namespace TreasureAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int action_buttons = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int action_down = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int action_left = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int action_right = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int action_up = 2131099652;
			
			// aapt resource value: 0x7f060021
			public const int add_player_button = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int dialog = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int game_rules = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int game_text = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int height_bar = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int height_bar_layout = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int height_bar_name = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int height_bar_value = 2131099665;
			
			// aapt resource value: 0x7f06002a
			public const int item1 = 2131099690;
			
			// aapt resource value: 0x7f060009
			public const int linear_layout = 2131099657;
			
			// aapt resource value: 0x7f060027
			public const int loading_spinner = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int name = 2131099688;
			
			// aapt resource value: 0x7f060017
			public const int player_bar_layout = 2131099671;
			
			// aapt resource value: 0x7f060014
			public const int portal_bar = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int portal_bar_layout = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int portal_bar_name = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int portal_bar_value = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int remove_player_button = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int root = 2131099648;
			
			// aapt resource value: 0x7f060025
			public const int rules_webview = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int start_game = 2131099683;
			
			// aapt resource value: 0x7f060008
			public const int start_new_game = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int swamp_bar = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int swamp_bar_layout = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int swamp_bar_name = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int swamp_bar_value = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int swamp_size_bar = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int swamp_size_bar_layout = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int swamp_size_bar_name = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int swamp_size_bar_value = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int through_check_box = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int through_checkbox_name = 2131099679;
			
			// aapt resource value: 0x7f060029
			public const int type = 2131099689;
			
			// aapt resource value: 0x7f06000c
			public const int width_bar = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int width_bar_layout = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int width_bar_name = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int width_bar_value = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int winner_text = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_game_over = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_game_settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_rules = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int edittext_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int player_prop = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int popup_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int action_go = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int action_strike = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int add_player = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int down = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int game_rules = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int height = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int left = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int new_game = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int player_count = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int portal_count = 2130968589;
			
			// aapt resource value: 0x7f040012
			public const int remove_player = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int right = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int start_game = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int swamp_count = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int swamp_size = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int through = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int up = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int width = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
